version: '3.8'

services:
  streamlit:
    build: 
      context: .
      dockerfile: ./compose/streamlit/template
    image: template
    container_name: template
    restart: always
    expose:
      - "8501"
    command: streamlit run streamlit-template/Template.py

  streamlit:
    build: 
      context: .
      dockerfile: ./compose/streamlit/umetaflow
    image: umetaflow
    container_name: umetaflow
    restart: always
    expose:
      - "8502"
    command: streamlit run umetaflow-gui/UmetaFlow.py
