version: '3.8'

services:
  streamlit:
    build: 
      context: .
      dockerfile: ./compose/streamlit/Dockerfile
    image: umetaflow
    container_name: umetaflow
    restart: always
    ports:
      - 8501:8501
    command: streamlit run umetaflow-gui/UmetaFlow.py