version: '3.8'

services:
  streamlit:
    build: 
      context: .
      dockerfile: ./compose/streamlit/Dockerfile
    image: streamlit_local
    container_name: umetaflow
    restart: always
    ports:
      - 8502:8502
    command: streamlit run umetaflow-gui/UmetaFlow.py