version: '3'

volumes:
  production_traefik: {}

services:
  streamlit:
    build: 
      context: .
      dockerfile: ./compose/streamlit/template
    image: template
    container_name: template
    restart: always
    expose:
      - "8501"
    command: streamlit run streamlit-template/Template.py

  streamlit:
    build: 
      context: .
      dockerfile: ./compose/streamlit/umetaflow
    image: umetaflow
    container_name: umetaflow
    restart: always
    expose:
      - "8502"
    command: streamlit run umetaflow-gui/UmetaFlow.py

  traefik:
    build:
      context: .
      dockerfile: ./compose/traefik/Dockerfile
    image: traefik_production
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"